.TH "/home/erin/Desktop/qt6Upgrade/voldigate/dependencies/libwallaby/module/create/public/kipr/create Directory Reference" 3 "Wed Sep 4 2024" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/erin/Desktop/qt6Upgrade/voldigate/dependencies/libwallaby/module/create/public/kipr/create Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcreate\&.h\fP"
.br
.ti -1c
.RI "file \fBcreate\&.hpp\fP"
.br
.ti -1c
.RI "file \fBcreate_codes\&.h\fP"
.br
.in -1c
