.TH "pages Directory Reference" 3 "Wed Sep 4 2024" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pages Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmainpage\&.h\fP"
.br
.ti -1c
.RI "file \fBtutorials_page\&.h\fP"
.br
.RI "a page filled with tutorials "
.in -1c
