.TH "/home/erin/Desktop/qt6Upgrade/voldigate/dependencies/libwallaby/module/analog/public/kipr/analog/analog.h" 3 "Wed Sep 4 2024" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/erin/Desktop/qt6Upgrade/voldigate/dependencies/libwallaby/module/analog/public/kipr/analog/analog.h
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBanalog\fP (int port)"
.br
.ti -1c
.RI "int \fBanalog8\fP (int port)"
.br
.ti -1c
.RI "int \fBanalog10\fP (int port)"
.br
.ti -1c
.RI "int \fBanalog12\fP (int port)"
.br
.ti -1c
.RI "int \fBanalog_et\fP (int port)"
.br
.ti -1c
.RI "void \fBset_analog_pullup\fP (int port, int pullup)"
.br
.ti -1c
.RI "int \fBget_analog_pullup\fP (int port)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBCopyright\fP
.RS 4
KISS Institute for Practical Robotics 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
