.TH "console" 3 "Wed Sep 4 2024" "Version 1.0.0" "libkipr" \" -*- nroff -*-
.ad l
.nh
.SH NAME
console \- Console
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBkipr::console::Console\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBEXPORT_SYM\fP void \fBconsole_clear\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
The functions defined here are functions relating to the console, or output window, of the UI\&. 
.SH "Function Documentation"
.PP 
.SS "\fBEXPORT_SYM\fP void console_clear ()"
Clears the UI's console\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for libkipr from the source code\&.
